ides:
  - id: dummy
    name: Dummy IDE
    data_dir: data/dummy
    fetcher: dummy
    start_version: "0.0.1"

  - id: eclipse
    name: Copilot for Eclipse
    data_dir: data/eclipse
    fetcher: eclipse
    start_version: all
    source_url: https://api.github.com/repos/microsoft/copilot-for-eclipse/releases

  - id: jetbrains
    name: GitHub Copilot for JetBrains
    data_dir: data/jetbrains
    fetcher: jetbrains
    start_version: all
    source_url: https://plugins.jetbrains.com/api/plugins/17718/updates
    plugin_url: https://plugins.jetbrains.com/plugin/17718-github-copilot/versions

  - id: xcode
    name: GitHub Copilot for Xcode
    data_dir: data/xcode
    fetcher: xcode
    start_version: all
    source_url: https://docs.github.com/en/copilot/reference/copilot-feature-matrix?tool=xcode

  - id: vim-neovim
    name: GitHub Copilot for Vim/Neovim
    data_dir: data/vim-neovim
    fetcher: copilot_vim
    source_url: https://docs.github.com/en/copilot/reference/copilot-feature-matrix?tool=vimneovim

  - id: vs-code
    name: GitHub Copilot for VS Code
    data_dir: data/vs-code
    fetcher: vs_code
    start_version: "1.75.0"
    source_url: https://code.visualstudio.com/feed.xml
    release_url_template: https://code.visualstudio.com/updates/v1_{n}

  - id: visual-studio-2026
    name: Visual Studio 2026
    data_dir: data/visual-studio-2026
    fetcher: visual_studio
    start_version: "17.14.0"
    source_url: https://learn.microsoft.com/en-us/visualstudio/releases/2026/release-notes

  - id: visual-studio-2022
    name: Visual Studio 2022
    data_dir: data/visual-studio-2022
    fetcher: visual_studio_2022
    start_version: "17.7"
    source_url: https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-history

  - id: sql-server-management-studio
    name: SQL Server Management Studio
    data_dir: data/sql-server-management-studio
    fetcher: ssms
    start_version: "21.0.0"
    source_urls:
      - https://learn.microsoft.com/en-us/ssms/release-notes-22
      - https://learn.microsoft.com/en-us/ssms/release-notes-21
